---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Check ansible version >=2.6.1"
      assert:
        msg: "Ansible version 2.6.1 or above is required to run this playbook"
        that:
          - ansible_version.string is version("2.6.1", ">=")
      tags:
        - always
        - check_version
  vars:
    ansible_connection: local

- hosts: ictnode
  gather_facts: true
  become: true
  become_method: sudo
  roles:
    - ict
