- import_tasks: deps_apt.yml
  tags:
    - deps
    - ict_deps_apt
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- import_tasks: deps_yum.yml
  tags:
    - deps
    - ict_deps_yum
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- import_tasks: firewalld.yml
  tags:
    - iri_firewalld
  when:
    - ansible_distribution == 'CentOS'
    - configure_firewall is defined and configure_firewall|bool == True

- import_tasks: ufw.yml
  tags:
    - iri_ufw
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - configure_firewall is defined and configure_firewall|bool == True

- import_tasks: config.yml
  tags:
    - ict_config

- include: ixi.yml
  tags:
    - ixi_config
